# Generated by Django 3.2 on 2021-05-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_productimage_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
