# Generated by Django 3.2 on 2021-05-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_productimages_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
